//! `casual-calc-import` — SpreadsheetML semantic import into the normalized
//! model.
//!
//! Phase 1A: maps a SpreadsheetML package into a [`Workbook`] — cell values
//! (number, bool, shared/inline string, error), **formulas parsed to an AST**
//! (`casual-calc-formula`) with the cached value preserved, **number formats**
//! (from `styles.xml` `cellXfs`), **merged ranges**, **frozen panes**, and
//! **defined names**. A [`CompatibilityReport`] records anything not fully
//! mapped (e.g. an unparseable formula is `Degraded`, keeping its cached value).
//! Import is deterministic: fixed workbook id, sequential sheet ids, and
//! insertion-ordered interning.
//!
//! See `docs/34-SPREADSHEETML-FIDELITY-ARCHITECTURE.md` and
//! `docs/22-NORMALIZED-SCHEMA.md`.

mod a1;
mod error;
mod read;
mod report;
mod styles;
mod theme;

pub use error::ImportError;
pub use report::{CompatibilityEntry, CompatibilityReport, ModelOutcome, RetentionOutcome};
pub use theme::stock_theme_slots;

use std::collections::{BTreeMap, BTreeSet, HashMap};

use casual_calc_formula::{Expr, parse as parse_formula, shift_references};
use casual_calc_model::{
    AutoFilter, Cell, CellComment, CellRange, CellRef, CellValue, CfRule, CommentReply,
    ConditionalFormat, CustomFilter, DataValidation, DefinedName, DvKind, DvOperator, ErrorValue,
    FilterOp, FilterRule, Id, IdGenerator, RetainedPart, RetainedRel, Sheet, SheetId,
    SheetVisibility, StringId, Workbook,
};
use casual_calc_ooxml::{OoxmlLimits, SpreadsheetPackage};

use a1::{parse_a1, parse_range};
use read::{
    RawCell, RawThreadedComment, parse_comments, parse_date1904, parse_defined_names,
    parse_persons, parse_retained_refs, parse_shared_strings, parse_table, parse_table_parts,
    parse_threaded_comments, parse_workbook_settings, parse_worksheet,
};
use styles::{StyleSheet, parse_styles};
use theme::{ThemePalette, parse_theme};

const WORKBOOK_NAMESPACE: u64 = 0x574b_0000_0000_0000; // "WK"
const SHEET_NAMESPACE: u64 = 0x5348_0000_0000_0000; // "SH"
const SHARED_STRINGS_PART: &str = "xl/sharedStrings.xml";
const STYLES_PART: &str = "xl/styles.xml";
const THEME_PART: &str = "xl/theme/theme1.xml";
/// Relationship type suffix binding a worksheet to its comments part.
const COMMENTS_REL_SUFFIX: &str = "/comments";
/// Relationship type suffix binding a worksheet to its threaded-comments part.
/// Deliberately distinct from [`COMMENTS_REL_SUFFIX`]: the two are matched by
/// suffix, and `…/threadedComment` does not end in `/comments`, so a package
/// carrying both binds each to the right reader.
const THREADED_COMMENTS_REL_SUFFIX: &str = "/threadedComment";
/// Relationship type suffix binding the workbook to its persons part.
const PERSONS_REL_SUFFIX: &str = "/person";
/// Most areas honoured from one `sqref`. Each area materializes its own model
/// entry (a validation copies its whole value list), so an adversarial part
/// with a huge area list must not become unbounded allocation.
const MAX_SQREF_AREAS: usize = 1024;

/// The result of importing a package: the model plus its compatibility report.
#[derive(Debug)]
pub struct Import {
    /// The normalized workbook.
    pub workbook: Workbook,
    /// What was mapped, degraded, or omitted.
    pub report: CompatibilityReport,
}

/// Copy the parts nothing above modelled into the workbook's retention set.
///
/// A part is retained when it is reachable from `workbook.xml` by a relationship
/// whose type we do not handle. The reference element inside `workbook.xml`
/// (`<externalReference r:id=…>`) travels too: a retained part nothing points at
/// is invisible to Excel, which is indistinguishable from having dropped it.
fn retain_unmodelled(
    package: &mut SpreadsheetPackage,
    workbook: &mut Workbook,
    sheet_parts: &[String],
) -> Result<(), ImportError> {
    let limits = OoxmlLimits::default();
    let content_types = package.content_type_overrides()?;
    let mut seen: BTreeSet<String> = BTreeSet::new();
    // Everything already generated by the writer, which must not be retained as
    // well — a stale copy would be written beside the fresh one.
    let generated: BTreeSet<String> = sheet_parts.iter().cloned().collect();

    // Breadth-first from the parts we do parse. A drawing reaches its charts and
    // images through its *own* relationships, so retention has to follow them:
    // keeping `drawing1.xml` while dropping the chart it references leaves a
    // reference to nothing, which Excel reports as a repair.
    let mut queue: Vec<String> = std::iter::once(package.workbook_part().to_owned())
        .chain(sheet_parts.iter().cloned())
        .collect();
    while let Some(source) = queue.pop() {
        for rel in package.relationships_of(&source, &limits)? {
            if rel.external
                || MODELLED_REL_SUFFIXES
                    .iter()
                    .any(|s| rel.rel_type.ends_with(s))
            {
                continue;
            }
            let target = resolve_part(&source, &rel.target);
            workbook.retained_rels.push(RetainedRel {
                source: source.clone(),
                id: rel.id,
                rel_type: rel.rel_type,
                target: rel.target,
            });
            if generated.contains(&target) || !seen.insert(target.clone()) {
                continue;
            }
            if !package.contains(&target) {
                continue;
            }
            let bytes = package.read_part(&target)?;
            workbook.retained_parts.push(RetainedPart {
                content_type: content_types.get(&format!("/{target}")).cloned(),
                path: target.clone(),
                bytes,
            });
            // Follow this part's own relationships in turn.
            queue.push(target);
        }
    }
    // Deterministic order: the queue is LIFO, so without this two runs over the
    // same package could emit the parts in different orders.
    workbook.retained_parts.sort_by(|a, b| a.path.cmp(&b.path));
    workbook
        .retained_rels
        .sort_by(|a, b| (&a.source, &a.id).cmp(&(&b.source, &b.id)));
    workbook.retained_rels.dedup();
    Ok(())
}

/// Relationship types `import_package` already turns into model state.
const MODELLED_REL_SUFFIXES: &[&str] = &[
    "/worksheet",
    "/sharedStrings",
    "/styles",
    "/theme",
    "/calcChain",
    "/vmlDrawing",
    "/hyperlink",
    "/table",
    COMMENTS_REL_SUFFIX,
    THREADED_COMMENTS_REL_SUFFIX,
    PERSONS_REL_SUFFIX,
];

/// Resolve a relationship target against the part that declared it.
fn resolve_part(source: &str, target: &str) -> String {
    if let Some(absolute) = target.strip_prefix('/') {
        return absolute.to_owned();
    }
    let dir = source.rsplit_once('/').map(|(d, _)| d).unwrap_or("");
    let mut parts: Vec<&str> = dir.split('/').filter(|p| !p.is_empty()).collect();
    for segment in target.split('/') {
        match segment {
            "." | "" => {}
            ".." => {
                parts.pop();
            }
            other => parts.push(other),
        }
    }
    parts.join("/")
}

/// Fold parsed `<threadedComment>` elements into a sheet's comment list.
///
/// The schema is flat: a root and its replies are siblings sharing a `ref`,
/// linked by `parentId`. Replies are attached in document order, which is the
/// order Excel writes and reads them.
///
/// A cell that already has a legacy note is **replaced**, not appended to: Excel
/// writes both parts for the same thread so that readers predating the 2018
/// schema still see something, and keeping both would show the opening remark
/// twice.
fn merge_threaded_comments(
    sheet: &mut Sheet,
    raw: Vec<RawThreadedComment>,
    persons: &BTreeMap<String, String>,
) {
    let author_of = |person_id: &Option<String>| -> Option<String> {
        person_id
            .as_ref()
            .and_then(|id| persons.get(id))
            .filter(|name| !name.is_empty())
            .cloned()
    };

    // Roots first, so a reply can never arrive before the thread it joins even
    // if a writer emitted them out of order.
    let (roots, replies): (Vec<_>, Vec<_>) = raw.into_iter().partition(|c| c.parent_id.is_none());

    let mut index_of: HashMap<String, usize> = HashMap::new();
    for root in roots {
        let Some(at) = parse_a1(&root.reference) else {
            continue;
        };
        let thread = CellComment {
            at,
            text: root.text,
            author: author_of(&root.person_id),
            created: root.date,
            resolved: root.done,
            replies: Vec::new(),
        };
        // Replace the legacy note for this cell if one was already read.
        match sheet
            .comments
            .iter()
            .position(|c| c.at.row == at.row && c.at.col == at.col)
        {
            Some(i) => {
                sheet.comments[i] = thread;
                index_of.insert(root.id, i);
            }
            None => {
                index_of.insert(root.id, sheet.comments.len());
                sheet.comments.push(thread);
            }
        }
    }

    for reply in replies {
        // A reply whose parent is missing has nowhere to go; dropping it is the
        // only option that does not invent a thread the file never had.
        let Some(&i) = reply.parent_id.as_ref().and_then(|p| index_of.get(p)) else {
            continue;
        };
        sheet.comments[i].replies.push(CommentReply {
            text: reply.text,
            author: author_of(&reply.person_id),
            created: reply.date,
        });
    }
}

/// Import a SpreadsheetML package into the normalized model.
pub fn import_package(bytes: Vec<u8>) -> Result<Import, ImportError> {
    let mut package = SpreadsheetPackage::open(bytes, OoxmlLimits::default())?;
    let mut report = CompatibilityReport::default();
    let mut workbook = Workbook::new(Id::from_parts(WORKBOOK_NAMESPACE, 1));

    // Shared strings → interned into the workbook, keeping index → StringId.
    let mut shared_ids: Vec<StringId> = Vec::new();
    if package.contains(SHARED_STRINGS_PART) {
        let xml = package.read_part(SHARED_STRINGS_PART)?;
        for value in parse_shared_strings(&xml)? {
            shared_ids.push(workbook.intern_rich_text(value));
        }
    }

    // Styles: the number-format code per cellXfs index. Pre-intern every xf in
    // order so the style-table order is canonical (cellXfs order) — this is what
    // lets the writer round-trip styles deterministically.
    // The theme palette must be read first: `styles.xml` states most colors as
    // a theme slot plus a tint, and those are exactly the colors Excel's
    // built-in cell styles use.
    let palette = if package.contains(THEME_PART) {
        let xml = package.read_part(THEME_PART)?;
        parse_theme(&xml)?
    } else {
        ThemePalette::default()
    };
    let stylesheet = if package.contains(STYLES_PART) {
        let xml = package.read_part(STYLES_PART)?;
        parse_styles(&xml, &palette)?
    } else {
        StyleSheet::default()
    };
    // Keep the theme itself, not just its resolved colours: a host offering a
    // colour picker should offer *this file's* theme, and the writer will need
    // it once theme linkage round-trips.
    workbook.theme_colors = palette.slots().to_vec();
    workbook.default_font_name = stylesheet.default_font_name.clone();
    workbook.default_font_size_hp = stylesheet.default_font_size_hp;
    workbook.cell_styles = stylesheet.cell_styles.clone();
    let xf_style_ids: Vec<Option<_>> = stylesheet
        .xf_styles
        .iter()
        .enumerate()
        .map(|(i, style)| {
            let mut style = style.clone();
            // Carry the named-style association. `xfId` 0 is Normal, which every
            // cell points at by default and which says nothing, so only a
            // non-zero link is worth keeping — otherwise every plain cell would
            // become "styled" and stop deduplicating.
            style.style_ref = stylesheet
                .xf_style_refs
                .get(i)
                .copied()
                .flatten()
                .filter(|id| *id != 0);
            if style.is_default() {
                None
            } else {
                Some(workbook.intern_style(style))
            }
        })
        .collect();

    // Own the sheet metadata so the package can be mutated (read) while looping.
    let sheet_meta: Vec<(String, String, String)> = package
        .sheets()
        .iter()
        .map(|s| (s.name.clone(), s.part.clone(), s.state.clone()))
        .collect();

    // The persons part is workbook-level and shared by every sheet's threads,
    // so it is read once here rather than per sheet.
    let workbook_part_name = package.workbook_part().to_owned();
    let persons: BTreeMap<String, String> = match package
        .related_part(
            &workbook_part_name,
            PERSONS_REL_SUFFIX,
            &OoxmlLimits::default(),
        )?
        .filter(|p| package.contains(p))
    {
        Some(part) => {
            let pxml = package.read_part(&part)?;
            parse_persons(&pxml)?.into_iter().collect()
        }
        None => BTreeMap::new(),
    };

    let mut sheet_ids = IdGenerator::new(SHEET_NAMESPACE);
    let mut sheet_ids_by_index: Vec<SheetId> = Vec::new();
    for (name, part, state) in sheet_meta {
        let xml = package.read_part(&part)?;
        let worksheet = parse_worksheet(&xml, &palette)?;
        let sheet_id = SheetId(sheet_ids.next_id());
        sheet_ids_by_index.push(sheet_id);
        let mut sheet = Sheet::new(sheet_id, name);
        // A hidden sheet that comes back visible exposes data its author put
        // away on purpose, so the state travels with the sheet.
        sheet.visibility = SheetVisibility::from_ooxml(&state);
        sheet.print = worksheet.print.clone();
        sheet.sort_state = worksheet.sort_state.clone();
        sheet.carried = worksheet.carried.clone();
        sheet.format_pr = worksheet.format_pr.clone();
        sheet.view.right_to_left = worksheet.right_to_left;
        sheet.view.show_formulas = worksheet.show_formulas;
        sheet.view.hide_zeros = worksheet.hide_zeros;
        sheet.view.tab_selected = worksheet.tab_selected;
        sheet.retained_refs = worksheet.retained_refs.clone();
        sheet.protection = worksheet
            .protection
            .clone()
            .map(|attrs| casual_calc_model::SheetProtection { attrs });

        // Shared formulas: Excel's fill-down writes the expression once, on the
        // group's master cell, and leaves every follower's `<f>` empty. Without
        // expanding them a filled column imports as one formula plus a stack of
        // cached constants — the formulas are simply gone. Collect the masters
        // first (document order puts them before their followers, but a
        // pre-pass keeps that from being load-bearing).
        let mut shared_masters: HashMap<u32, (CellRef, Expr)> = HashMap::new();
        for raw in &worksheet.cells {
            let (Some(si), Some(text)) = (raw.shared_index, raw.formula.as_deref()) else {
                continue;
            };
            if text.trim().is_empty() {
                continue;
            }
            if let Some(at) = parse_a1(&raw.reference)
                && let Ok(expr) = parse_formula(text)
            {
                shared_masters.entry(si).or_insert((at, expr));
            }
        }

        for raw in worksheet.cells {
            let Some(cell_ref) = parse_a1(&raw.reference) else {
                report.record(
                    "cellRef",
                    ModelOutcome::Omitted,
                    RetentionOutcome::NotRetained,
                );
                continue;
            };
            let value = map_value(&raw, &shared_ids, &mut workbook, &mut report);
            let mut cell = Cell::value(value);
            if let Some(index) = raw.style_index
                && let Some(Some(style_id)) = xf_style_ids.get(index as usize)
            {
                cell.style = Some(*style_id);
            }
            match raw.formula.as_deref() {
                Some(text) if !text.trim().is_empty() => match parse_formula(text) {
                    Ok(expr) => {
                        cell.formula = Some(workbook.store_formula(expr));
                        report.record("f", ModelOutcome::Mapped, RetentionOutcome::NotApplicable);
                    }
                    Err(_) => {
                        // Cached value kept; the formula text did not parse.
                        report.record("f", ModelOutcome::Degraded, RetentionOutcome::NotRetained);
                    }
                },
                // An empty `<f>` is a shared-formula follower: rebuild it from
                // its master, shifted by the row/column delta. `$` anchors stay
                // put — the same copy/fill semantics the shifter gives the UI.
                Some(_) => {
                    let rebuilt = raw.shared_index.and_then(|si| shared_masters.get(&si)).map(
                        |(at, expr)| {
                            shift_references(
                                expr,
                                i64::from(cell_ref.row) - i64::from(at.row),
                                i64::from(cell_ref.col) - i64::from(at.col),
                            )
                        },
                    );
                    match rebuilt {
                        Some(expr) => {
                            cell.formula = Some(workbook.store_formula(expr));
                            report.record(
                                "f",
                                ModelOutcome::Mapped,
                                RetentionOutcome::NotApplicable,
                            );
                        }
                        None => {
                            report.record(
                                "f",
                                ModelOutcome::Degraded,
                                RetentionOutcome::NotRetained,
                            );
                        }
                    }
                }
                None => {}
            }
            if !cell.is_blank() {
                sheet.cells.set(cell_ref, cell);
            }
        }

        for reference in &worksheet.merges {
            match parse_range(reference) {
                Some(range) => sheet.merges.push(range),
                None => report.record(
                    "mergeCell",
                    ModelOutcome::Omitted,
                    RetentionOutcome::NotRetained,
                ),
            }
        }
        if let Some((frozen_rows, frozen_cols)) = worksheet.frozen {
            sheet.view.frozen_rows = frozen_rows;
            sheet.view.frozen_cols = frozen_cols;
        }
        if let Some(zoom) = worksheet.zoom {
            sheet.view.zoom = zoom;
        }
        sheet.view.hide_gridlines = worksheet.hide_gridlines;
        sheet.view.hide_headers = worksheet.hide_headers;
        sheet.columns.default = worksheet.col_default;
        sheet.columns.sizes = worksheet.col_sizes;
        sheet.rows.default = worksheet.row_default;
        sheet.rows.sizes = worksheet.row_sizes;
        sheet.hidden_rows = worksheet.hidden_rows;
        sheet.hidden_cols = worksheet.hidden_cols;
        sheet.row_outline_levels = worksheet.row_outline_levels;
        sheet.col_outline_levels = worksheet.col_outline_levels;
        sheet.collapsed_rows = worksheet.collapsed_rows;
        sheet.collapsed_cols = worksheet.collapsed_cols;
        if let Some(outline) = worksheet.outline {
            sheet.outline = outline;
        }
        sheet.tab_color = worksheet.tab_color;

        // Autofilter. The rows it hides arrive as ordinary `hidden="1"` rows —
        // OOXML has no separate marker — so they land in `hidden_rows` here and
        // the session re-derives `filter_hidden` from the rules once formatting
        // is available (display text is what a checklist matches on).
        if let Some(reference) = worksheet.auto_filter.as_deref()
            && let Some(range) = a1::parse_range(reference)
        {
            let mut filter = AutoFilter::new(range);
            for fc in worksheet.filter_columns {
                // A refinement takes precedence: a filterColumn holding one has
                // no <filters> or <customFilters> to read instead.
                let rule = if let Some((element, attrs)) = fc.unevaluated.clone() {
                    FilterRule::Unevaluated { element, attrs }
                } else if fc.saw_filters {
                    let mut values = fc.values;
                    if fc.blank {
                        // `blank="1"` is the checklist's "(Blanks)" entry, which
                        // the model carries as the empty string.
                        values.push(String::new());
                    }
                    // An empty checklist would select nothing at all; Excel does
                    // not write one, and honouring it would blank the sheet.
                    if values.is_empty() {
                        continue;
                    }
                    FilterRule::Values(values)
                } else {
                    let mut ops = fc.custom.into_iter().map(|(op, value)| CustomFilter {
                        op: FilterOp::from_ooxml(&op),
                        value,
                    });
                    let Some(first) = ops.next() else {
                        continue; // a filterColumn with neither kind of child
                    };
                    FilterRule::Custom {
                        first,
                        second: ops.next(),
                        and: fc.custom_and,
                    }
                };
                filter.rules.insert(fc.col_id, rule);
            }
            sheet.auto_filter = Some(filter);
        }

        // Data validations, every kind. Only a `list` rule's inline quoted CSV is
        // expanded into values; the other kinds keep their operands as the raw
        // formula text, which is what they are.
        for raw in worksheet.validations {
            let kind = DvKind::from_ooxml(&raw.kind);
            let trimmed = raw.formula1.trim();
            let values: Vec<String> = if kind == DvKind::List
                && trimmed.len() >= 2
                && trimmed.starts_with('"')
                && trimmed.ends_with('"')
            {
                trimmed[1..trimmed.len() - 1]
                    .split(',')
                    .map(|s| s.trim().to_owned())
                    .filter(|s| !s.is_empty())
                    .collect()
            } else {
                Vec::new()
            };
            // A list whose values are a range reference rather than an inline
            // CSV keeps its formula, so the rule survives even though the editor
            // cannot offer the dropdown yet.
            if kind == DvKind::None && values.is_empty() && raw.formula1.trim().is_empty() {
                continue;
            }
            // An sqref is a space-separated list of areas; taking only the first
            // silently dropped the validation from every other area it covers.
            // Bounded, because each area copies the value list: a hand-written
            // sqref with tens of thousands of areas would otherwise turn a small
            // part into millions of heap strings.
            for area in raw.sqref.split_whitespace().take(MAX_SQREF_AREAS) {
                let range =
                    parse_range(area).or_else(|| parse_a1(area).map(|c| CellRange::new(c, c)));
                if let Some(range) = range {
                    sheet.validations.push(DataValidation {
                        values: values.clone(),
                        kind,
                        operator: DvOperator::from_ooxml(&raw.operator),
                        formula1: raw.formula1.clone(),
                        formula2: raw.formula2.clone(),
                        allow_blank: raw.allow_blank,
                        error_title: raw.error_title.clone(),
                        error_text: raw.error_text.clone(),
                        prompt_title: raw.prompt_title.clone(),
                        prompt_text: raw.prompt_text.clone(),
                        ..DataValidation::none(range)
                    });
                }
            }
            let sqref = raw.sqref;
            if sqref.split_whitespace().count() > MAX_SQREF_AREAS {
                report.record(
                    "dataValidation/sqref",
                    ModelOutcome::Degraded,
                    RetentionOutcome::NotRetained,
                );
            }
        }

        // Conditional formatting: resolve each cfRule's fill via its dxfId, its
        // range via the sqref, and its predicate via type/operator/formulas.
        // Rules without a solid fill (the only kind modeled) are skipped.
        for raw in worksheet.conditional_formats {
            // Colour scales and data bars carry their own colours and have no
            // dxfId, so the fill lookup must not gate them out.
            let scale_or_bar = matches!(raw.kind.as_str(), "colorScale" | "dataBar");
            let fill = match raw
                .dxf_id
                .and_then(|id| stylesheet.dxf_fills.get(id).cloned().flatten())
            {
                Some(f) => f,
                None if scale_or_bar => String::new(),
                None => continue,
            };
            let num = |i: usize| {
                raw.formulas
                    .get(i)
                    .and_then(|s| s.trim().parse::<f64>().ok())
            };
            let rule = match (raw.kind.as_str(), raw.operator.as_str()) {
                ("cellIs", "greaterThan") => num(0).map(CfRule::GreaterThan),
                ("cellIs", "lessThan") => num(0).map(CfRule::LessThan),
                ("cellIs", "equal") => num(0).map(CfRule::EqualTo),
                ("cellIs", "between") => match (num(0), num(1)) {
                    (Some(a), Some(b)) => Some(CfRule::Between(a, b)),
                    _ => None,
                },
                ("containsText", _) => raw.text.clone().map(CfRule::TextContains),
                ("colorScale", _) if raw.colors.len() >= 2 => {
                    Some(CfRule::ColorScale(raw.colors.clone()))
                }
                ("dataBar", _) => raw.colors.first().cloned().map(CfRule::DataBar),
                ("top10", _) => Some(CfRule::Top10 {
                    // A rank of zero would select nothing; Excel's minimum is 1.
                    rank: raw.rank.max(1),
                    bottom: raw.bottom,
                    percent: raw.percent,
                }),
                ("aboveAverage", _) => Some(CfRule::AboveAverage {
                    below: !raw.above_average,
                    equal: raw.equal_average,
                }),
                ("duplicateValues", _) => Some(CfRule::DuplicateValues { unique: false }),
                ("uniqueValues", _) => Some(CfRule::DuplicateValues { unique: true }),
                _ => None,
            };
            if let Some(rule) = rule {
                // One rule per area of the sqref — a cfRule covering "A1:A9 C1:C9"
                // used to apply to the first area only. Bounded as above.
                for area in raw.sqref.split_whitespace().take(MAX_SQREF_AREAS) {
                    let Some(range) =
                        parse_range(area).or_else(|| parse_a1(area).map(|c| CellRange::new(c, c)))
                    else {
                        continue;
                    };
                    sheet.conditional_formats.push(ConditionalFormat {
                        range,
                        rule: rule.clone(),
                        fill: fill.clone(),
                        font_color: None,
                        bold: false,
                        priority: raw.priority,
                        stop_if_true: raw.stop_if_true,
                    });
                }
            }
        }

        // Cell comments: follow the sheet's own relationships. Guessing
        // `xl/comments{index+1}.xml` only agrees with files this writer
        // produced — in anyone else's package the numbering follows which
        // sheets *have* comments, so sheet 2's notes landed on sheet 1 (or on
        // no sheet at all).
        // (A comments part is only reachable through a relationship, so a sheet
        // without one simply has no notes — there is nothing to fall back to.)
        let comments_part = package
            .related_part(&part, COMMENTS_REL_SUFFIX, &OoxmlLimits::default())?
            .filter(|p| package.contains(p));
        if let Some(comments_part) = comments_part {
            let cxml = package.read_part(&comments_part)?;
            for (reference, author, text) in parse_comments(&cxml)? {
                if !text.is_empty()
                    && let Some(at) = parse_a1(&reference)
                {
                    sheet.comments.push(CellComment::note(at, text, author));
                }
            }
        }

        // Hyperlinks: the `ref` and `location` are in the worksheet, but an
        // external target lives in the sheet's relationships and is reachable
        // only through the link's own `r:id`. Resolving the two here keeps the
        // model free of relationship ids, which are a packaging detail with no
        // meaning once the file is open.
        if !worksheet.hyperlinks.is_empty() {
            let rels = package.relationships_of(&part, &OoxmlLimits::default())?;
            for raw in &worksheet.hyperlinks {
                let Some(range) = parse_range(&raw.reference) else {
                    continue;
                };
                let target = raw.rel_id.as_ref().and_then(|id| {
                    rels.iter()
                        .find(|r| &r.id == id)
                        // Only an external relationship is a link destination;
                        // an internal one points at a part in the package,
                        // which is not something to navigate to.
                        .filter(|r| r.external)
                        .map(|r| r.target.clone())
                });
                if target.is_none() && raw.location.is_none() {
                    // Neither destination resolved, so there is nothing to link
                    // to; keeping it would render as a dead link.
                    continue;
                }
                sheet.hyperlinks.push(casual_calc_model::Hyperlink {
                    range,
                    target,
                    location: raw.location.clone(),
                    tooltip: raw.tooltip.clone(),
                    display: raw.display.clone(),
                });
            }
        }

        // Tables (ListObjects). Each `<tablePart r:id>` in the worksheet names
        // a part through the sheet's own relationships, the same indirection
        // comments use — guessing `xl/tables/table{n}.xml` would bind sheet 2's
        // table to sheet 1 in anyone else's package.
        let table_ids = parse_table_parts(&xml)?;
        if !table_ids.is_empty() {
            let rels = package.relationships_of(&part, &OoxmlLimits::default())?;
            for id in table_ids {
                let Some(rel) = rels.iter().find(|r| r.id == id) else {
                    continue;
                };
                let target = resolve_part(&part, &rel.target);
                if !package.contains(&target) {
                    continue;
                }
                let txml = package.read_part(&target)?;
                let Some(raw) = parse_table(&txml)? else {
                    continue;
                };
                let Some(range) = raw.attrs.get("ref").and_then(|r| parse_range(r)) else {
                    continue;
                };
                let attr_u32 = |k: &str, default: u32| {
                    raw.attrs
                        .get(k)
                        .and_then(|v| v.parse().ok())
                        .unwrap_or(default)
                };
                let name = raw.attrs.get("name").cloned().unwrap_or_default();
                let mut attrs = raw.attrs.clone();
                // The interpreted attributes are removed from the verbatim map,
                // or they would be written twice — once from the field and once
                // from the map, with the stale copy winning on the next read.
                for key in [
                    "ref",
                    "name",
                    "displayName",
                    "id",
                    "headerRowCount",
                    "totalsRowCount",
                ] {
                    attrs.remove(key);
                }
                sheet.tables.push(casual_calc_model::Table {
                    id: attr_u32("id", 1),
                    display_name: raw
                        .attrs
                        .get("displayName")
                        .cloned()
                        .unwrap_or_else(|| name.clone()),
                    name,
                    range,
                    header_row_count: attr_u32("headerRowCount", 1),
                    totals_row_count: attr_u32("totalsRowCount", 0),
                    columns: raw.columns,
                    auto_filter_ref: raw.auto_filter_ref,
                    style: raw.style,
                    attrs,
                });
            }
        }

        // Threaded comments (the 2018 parts) carry the timestamps, the replies
        // and the resolved flag. Excel writes a legacy note alongside them for
        // readers that predate the schema, so a cell can appear in both parts —
        // the threaded one is the fuller record and replaces what the legacy
        // pass just read, rather than adding a duplicate beside it.
        let threaded_part = package
            .related_part(&part, THREADED_COMMENTS_REL_SUFFIX, &OoxmlLimits::default())?
            .filter(|p| package.contains(p));
        if let Some(threaded_part) = threaded_part {
            let txml = package.read_part(&threaded_part)?;
            let raw = parse_threaded_comments(&txml)?;
            merge_threaded_comments(&mut sheet, raw, &persons);
        }

        workbook.sheets.push(sheet);
    }

    // Retention: keep every part the semantic reader did not consume, plus the
    // relationship that reaches it and the reference that names it. This is what
    // separates "we do not model charts" from "we delete charts" — a workbook
    // people already have work in must survive a save even where we understand
    // nothing about the feature.
    let sheet_parts: Vec<String> = package.sheets().iter().map(|s| s.part.clone()).collect();
    retain_unmodelled(&mut package, &mut workbook, &sheet_parts)?;

    // Defined names, resolved against the sheet ids assigned above.
    let workbook_part = package.workbook_part().to_owned();
    let workbook_xml = package.read_part(&workbook_part)?;
    // The date epoch has to be known before any date is displayed, and has to
    // be written back or the serials silently change meaning.
    workbook.date1904 = parse_date1904(&workbook_xml)?;
    workbook.settings = parse_workbook_settings(&workbook_xml)?;
    workbook.retained_refs = parse_retained_refs(&workbook_xml)?;
    for (name, local_sheet, refers_to) in parse_defined_names(&workbook_xml)? {
        match parse_formula(&refers_to) {
            Ok(formula) => {
                let sheet = local_sheet.and_then(|i| sheet_ids_by_index.get(i as usize).copied());
                workbook.defined_names.push(DefinedName {
                    name,
                    sheet,
                    formula,
                });
                report.record(
                    "definedName",
                    ModelOutcome::Mapped,
                    RetentionOutcome::NotApplicable,
                );
            }
            Err(_) => report.record(
                "definedName",
                ModelOutcome::Degraded,
                RetentionOutcome::NotRetained,
            ),
        }
    }

    workbook.validate()?;
    Ok(Import { workbook, report })
}

fn map_value(
    raw: &RawCell,
    shared: &[StringId],
    workbook: &mut Workbook,
    report: &mut CompatibilityReport,
) -> CellValue {
    match raw.cell_type.as_deref() {
        None | Some("n") => raw
            .value
            .as_deref()
            .and_then(|s| s.parse::<f64>().ok())
            .map(CellValue::Number)
            .unwrap_or(CellValue::Empty),
        Some("b") => CellValue::Bool(raw.value.as_deref() == Some("1")),
        Some("s") => match raw
            .value
            .as_deref()
            .and_then(|s| s.parse::<usize>().ok())
            .and_then(|i| shared.get(i).copied())
        {
            Some(id) => CellValue::SharedString(id),
            None => {
                report.record("s", ModelOutcome::Omitted, RetentionOutcome::NotRetained);
                CellValue::Empty
            }
        },
        Some("str") => raw
            .value
            .as_deref()
            .map(|s| CellValue::InlineString(workbook.intern_string(s)))
            .unwrap_or(CellValue::Empty),
        Some("inlineStr") => raw
            .inline
            .as_deref()
            .map(|s| CellValue::InlineString(workbook.intern_string(s)))
            .unwrap_or(CellValue::Empty),
        Some("e") => match raw.value.as_deref().and_then(parse_error) {
            Some(error) => CellValue::Error(error),
            None => {
                report.record("e", ModelOutcome::Omitted, RetentionOutcome::NotRetained);
                CellValue::Empty
            }
        },
        Some(other) => {
            report.record(other, ModelOutcome::Omitted, RetentionOutcome::NotRetained);
            CellValue::Empty
        }
    }
}

fn parse_error(token: &str) -> Option<ErrorValue> {
    Some(match token {
        "#REF!" => ErrorValue::Ref,
        "#VALUE!" => ErrorValue::Value,
        "#DIV/0!" => ErrorValue::Div0,
        "#N/A" => ErrorValue::Na,
        "#NAME?" => ErrorValue::Name,
        "#NULL!" => ErrorValue::Null,
        "#NUM!" => ErrorValue::Num,
        "#SPILL!" => ErrorValue::Spill,
        _ => return None,
    })
}

#[cfg(test)]
mod tests;
