[package]
name = "casual-calc-ods"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
casual-calc-formula = { path = "../casual-calc-formula" }
casual-calc-import = { path = "../casual-calc-import" }
casual-calc-model = { path = "../casual-calc-model" }
quick-xml = "0.41"
zip = { version = "2", default-features = false, features = ["deflate"] }

[lints]
workspace = true
