//! Files this project did not write.
//!
//! Every other fidelity test in the repository asserts against a document whose
//! shape we chose — written by our own exporter, or generated by our own script.
//! That is circular in the way that matters: it proves the importer agrees with
//! the exporter, and says nothing about whether either agrees with Excel.
//!
//! These are real files produced by Microsoft Excel, taken from Apache POI's
//! test data (Apache-2.0, provenance recorded in `fixtures/manifest.json`). They
//! contain the things a real document contains and a hand-written fixture does
//! not: a chart, a classic header, conditional formatting, defined names,
//! several hundred rows of somebody's actual data, and parts this project has
//! never emitted.
//!
//! What is asserted is deliberately modest, and it is the assertion that was
//! missing rather than a better one. An importer that opens a real file and
//! produces a sheet with cells in it has cleared the bar these files exist to
//! set; whether every colour matches is the oracle's job. Silently returning an
//! empty workbook is **not** clearing it, which is why the cell count is checked
//! — that is the shape a "successful" import takes when it has quietly skipped
//! everything it did not recognise.

use std::path::PathBuf;

fn corpus() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/corpus")
}

/// Every corpus file, or nothing if the corpus is absent.
fn files() -> Vec<PathBuf> {
    let Ok(entries) = std::fs::read_dir(corpus()) else {
        return Vec::new();
    };
    let mut found: Vec<PathBuf> = entries
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|e| e == "xlsx"))
        .collect();
    // Sorted, so a failure names the same file on every machine.
    found.sort();
    found
}

#[test]
fn the_corpus_is_present() {
    // A guard against every test below passing because there is nothing to run
    // them on. A corpus that quietly disappears takes its coverage with it and
    // leaves the suite green.
    assert!(
        files().len() >= 5,
        "expected the real-producer corpus in fixtures/corpus; found {:?}",
        files()
    );
}

#[test]
fn every_real_file_opens() {
    let mut total_cells = 0usize;
    let mut opened = 0usize;
    let mut refused: Vec<String> = Vec::new();
    for path in files() {
        let bytes = std::fs::read(&path).expect("the file is readable");
        let name = path.file_name().unwrap().to_string_lossy().into_owned();

        // Opened, or refused with a reason. Both are correct answers and the
        // corpus contains both: `49609.xlsx` is a package with no
        // `_rels/.rels`, which is not a spreadsheet however much it is named
        // like one, and refusing it is the right behaviour rather than a gap.
        //
        // What neither may be is a panic or a hang, and that is the assertion —
        // these are files this project did not write, arriving from anywhere,
        // and "we crash on this one" is not a thing a user can work around.
        match casual_calc_import::import_package(bytes) {
            Ok(import) => {
                assert!(
                    !import.workbook.sheets.is_empty(),
                    "{name} opened with no sheets at all"
                );
                opened += 1;
                total_cells += import
                    .workbook
                    .sheets
                    .iter()
                    .map(|sheet| sheet.cells.iter().count())
                    .sum::<usize>();
            }
            Err(why) => {
                refused.push(format!("{name}: {why}"));
            }
        }
    }

    // Corpus-wide rather than per file, and the reason is a finding rather than
    // a convenience. The first version asserted every file yields cells, and
    // `47668.xlsx` failed it — correctly: that file is a workbook containing
    // only an image, its `<sheetData/>` is genuinely empty, and the importer was
    // right. A real corpus contains files like that, which is exactly why it is
    // worth having and why an assumption written against documents we wrote does
    // not survive contact with it.
    //
    // What the count still catches is the failure worth catching: an importer
    // that recognises nothing, reports success and returns an empty workbook
    // looks precisely like one that worked, until somebody notices their data is
    // gone. That cannot hide behind a total this size.
    assert!(
        total_cells > 100,
        "the whole corpus yielded only {total_cells} cells, which is what silently \
         importing nothing looks like"
    );
    // A guard against the refusals quietly becoming the rule. If most of a
    // corpus of real files stops opening, this suite should say so rather than
    // pass because every failure was a *clean* failure.
    assert!(
        opened * 2 > files().len(),
        "only {opened} of {} opened; refusals: {refused:#?}",
        files().len()
    );
}

#[test]
fn opening_a_real_file_twice_gives_the_same_workbook() {
    // Determinism against input nobody here designed. The engine's determinism
    // is asserted all over the place against documents we wrote; this asks the
    // same question of files whose parts arrive in an order we did not choose,
    // which is where an incidental dependence on iteration order would show.
    for path in files() {
        let bytes = std::fs::read(&path).expect("the file is readable");
        let name = path.file_name().unwrap().to_string_lossy().into_owned();
        let (Ok(once), Ok(twice)) = (
            casual_calc_import::import_package(bytes.clone()),
            casual_calc_import::import_package(bytes),
        ) else {
            // Refused, and refused both times — determinism is only a question
            // for the files that open. A package with no `_rels/.rels` is not a
            // spreadsheet however it is named, and saying so twice is
            // consistent behaviour rather than a gap.
            continue;
        };
        assert_eq!(
            once.workbook.to_snapshot().unwrap(),
            twice.workbook.to_snapshot().unwrap(),
            "{name} imported differently the second time"
        );
    }
}

/// Strict Open XML, which Excel can save and which uses different namespaces.
///
/// Recorded as a defect on the strength of a grep — 22 matches for the
/// transitional namespace, none for the strict one — and the grep was right
/// about the counts and wrong about the conclusion. The readers match element
/// **local names** rather than namespace URIs, in forty-nine places, so a strict
/// file parses without anything special. It was designed that way; nobody had
/// checked it since.
///
/// The test exists so it stays true. A reader tightened later to match on a
/// namespace would be a reasonable-looking change that silently stops opening
/// files Excel produces, and nothing else here would notice.
#[test]
fn a_strict_open_xml_workbook_reads_the_same_as_a_transitional_one() {
    const TRANSITIONAL_MAIN: &str = "http://schemas.openxmlformats.org/spreadsheetml/2006/main";
    const STRICT_MAIN: &str = "http://purl.oclc.org/ooxml/spreadsheetml/main";
    const TRANSITIONAL_REL: &str =
        "http://schemas.openxmlformats.org/officeDocument/2006/relationships";
    const STRICT_REL: &str = "http://purl.oclc.org/ooxml/officeDocument/relationships";

    for path in files() {
        let bytes = std::fs::read(&path).expect("readable");
        let name = path.file_name().unwrap().to_string_lossy().into_owned();
        let Ok(transitional) = casual_calc_import::import_package(bytes.clone()) else {
            continue; // refused either way; nothing to compare
        };

        // Rewrite every part's namespaces, which is the difference between the
        // two flavours as far as a reader is concerned.
        let mut strict = Vec::new();
        {
            let reader = std::io::Cursor::new(&bytes);
            let mut zin = zip::ZipArchive::new(reader).expect("a package");
            let mut zout = zip::ZipWriter::new(std::io::Cursor::new(&mut strict));
            for i in 0..zin.len() {
                let mut entry = zin.by_index(i).expect("entry");
                let entry_name = entry.name().to_owned();
                let mut data = Vec::new();
                std::io::Read::read_to_end(&mut entry, &mut data).expect("read");
                if entry_name.ends_with(".xml")
                    && let Ok(text) = String::from_utf8(data.clone())
                {
                    data = text
                        .replace(TRANSITIONAL_MAIN, STRICT_MAIN)
                        .replace(TRANSITIONAL_REL, STRICT_REL)
                        .into_bytes();
                }
                zout.start_file(entry_name, zip::write::SimpleFileOptions::default())
                    .expect("start");
                std::io::Write::write_all(&mut zout, &data).expect("write");
            }
            zout.finish().expect("finish");
        }

        let strict = casual_calc_import::import_package(strict)
            .unwrap_or_else(|e| panic!("{name} in strict form was refused: {e}"));

        // The *modelled* content, not the whole snapshot. ADR-007's retained
        // parts are preserved byte for byte, and this test rewrote namespaces
        // inside them — so a snapshot comparison fails on a difference the test
        // itself introduced. That is what the first version did, and the
        // "failure" was mine rather than the importer's.
        let seen = |import: &casual_calc_import::Import| -> Vec<String> {
            import
                .workbook
                .sheets
                .iter()
                .map(|sheet| {
                    let mut cells: Vec<String> = sheet
                        .cells
                        .iter()
                        .map(|(at, cell)| format!("{}:{}={:?}", at.row, at.col, cell.value))
                        .collect();
                    cells.sort();
                    format!("{}|{}", sheet.name, cells.join(","))
                })
                .collect()
        };
        assert_eq!(
            seen(&strict),
            seen(&transitional),
            "{name} read differently in strict form"
        );
    }
}
