//! Files this project did not write.
//!
//! Every other fidelity test in the repository asserts against a document whose
//! shape we chose — written by our own exporter, or generated by our own script.
//! That is circular in the way that matters: it proves the importer agrees with
//! the exporter, and says nothing about whether either agrees with Excel.
//!
//! These are real files produced by Microsoft Excel, taken from Apache POI's
//! test data (Apache-2.0, provenance recorded in `fixtures/manifest.json`). They
//! contain the things a real document contains and a hand-written fixture does
//! not: a chart, a classic header, conditional formatting, defined names,
//! several hundred rows of somebody's actual data, and parts this project has
//! never emitted.
//!
//! What is asserted is deliberately modest, and it is the assertion that was
//! missing rather than a better one. An importer that opens a real file and
//! produces a sheet with cells in it has cleared the bar these files exist to
//! set; whether every colour matches is the oracle's job. Silently returning an
//! empty workbook is **not** clearing it, which is why the cell count is checked
//! — that is the shape a "successful" import takes when it has quietly skipped
//! everything it did not recognise.

use std::path::PathBuf;

fn corpus() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/corpus")
}

/// Every corpus file, or nothing if the corpus is absent.
fn files() -> Vec<PathBuf> {
    let Ok(entries) = std::fs::read_dir(corpus()) else {
        return Vec::new();
    };
    let mut found: Vec<PathBuf> = entries
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|e| e == "xlsx"))
        .collect();
    // Sorted, so a failure names the same file on every machine.
    found.sort();
    found
}

#[test]
fn the_corpus_is_present() {
    // A guard against every test below passing because there is nothing to run
    // them on. A corpus that quietly disappears takes its coverage with it and
    // leaves the suite green.
    assert!(
        files().len() >= 5,
        "expected the real-producer corpus in fixtures/corpus; found {:?}",
        files()
    );
}

#[test]
fn every_real_file_opens() {
    let mut total_cells = 0usize;
    let mut opened = 0usize;
    let mut refused: Vec<String> = Vec::new();
    for path in files() {
        let bytes = std::fs::read(&path).expect("the file is readable");
        let name = path.file_name().unwrap().to_string_lossy().into_owned();

        // Opened, or refused with a reason. Both are correct answers and the
        // corpus contains both: `49609.xlsx` is a package with no
        // `_rels/.rels`, which is not a spreadsheet however much it is named
        // like one, and refusing it is the right behaviour rather than a gap.
        //
        // What neither may be is a panic or a hang, and that is the assertion —
        // these are files this project did not write, arriving from anywhere,
        // and "we crash on this one" is not a thing a user can work around.
        match casual_calc_import::import_package(bytes) {
            Ok(import) => {
                assert!(
                    !import.workbook.sheets.is_empty(),
                    "{name} opened with no sheets at all"
                );
                opened += 1;
                total_cells += import
                    .workbook
                    .sheets
                    .iter()
                    .map(|sheet| sheet.cells.iter().count())
                    .sum::<usize>();
            }
            Err(why) => {
                refused.push(format!("{name}: {why}"));
            }
        }
    }

    // Corpus-wide rather than per file, and the reason is a finding rather than
    // a convenience. The first version asserted every file yields cells, and
    // `47668.xlsx` failed it — correctly: that file is a workbook containing
    // only an image, its `<sheetData/>` is genuinely empty, and the importer was
    // right. A real corpus contains files like that, which is exactly why it is
    // worth having and why an assumption written against documents we wrote does
    // not survive contact with it.
    //
    // What the count still catches is the failure worth catching: an importer
    // that recognises nothing, reports success and returns an empty workbook
    // looks precisely like one that worked, until somebody notices their data is
    // gone. That cannot hide behind a total this size.
    assert!(
        total_cells > 100,
        "the whole corpus yielded only {total_cells} cells, which is what silently \
         importing nothing looks like"
    );
    // A guard against the refusals quietly becoming the rule. If most of a
    // corpus of real files stops opening, this suite should say so rather than
    // pass because every failure was a *clean* failure.
    assert!(
        opened * 2 > files().len(),
        "only {opened} of {} opened; refusals: {refused:#?}",
        files().len()
    );
}

#[test]
fn opening_a_real_file_twice_gives_the_same_workbook() {
    // Determinism against input nobody here designed. The engine's determinism
    // is asserted all over the place against documents we wrote; this asks the
    // same question of files whose parts arrive in an order we did not choose,
    // which is where an incidental dependence on iteration order would show.
    for path in files() {
        let bytes = std::fs::read(&path).expect("the file is readable");
        let name = path.file_name().unwrap().to_string_lossy().into_owned();
        let (Ok(once), Ok(twice)) = (
            casual_calc_import::import_package(bytes.clone()),
            casual_calc_import::import_package(bytes),
        ) else {
            // Refused, and refused both times — determinism is only a question
            // for the files that open. A package with no `_rels/.rels` is not a
            // spreadsheet however it is named, and saying so twice is
            // consistent behaviour rather than a gap.
            continue;
        };
        assert_eq!(
            once.workbook.to_snapshot().unwrap(),
            twice.workbook.to_snapshot().unwrap(),
            "{name} imported differently the second time"
        );
    }
}
