/// Command id -> icon, for the ribbon and the Sheets chrome (`UX-RIB-04`).
///
/// **The editor's menus carry no icons at all** — the menu builder emits none,
/// which is correct for a menu and is why the first ribbon rendered as a wall
/// of words: every proxy cloned its source's glyph and 99 of them found nothing
/// to clone. This table is the fix, and the icons are the ones already drawn
/// for the `docs/prototypes/ribbon-2026.html` study, lifted whole rather than
/// redrawn, so the two agree by construction.
///
/// A name resolves to `#i-<name>` at 16px and `#l-<name>` at 20px. Most have
/// both; where only one exists the entry names each explicitly. A command with
/// no entry draws its label alone, which is the honest fallback — a wrong icon
/// is worse than none, because it teaches the wrong thing.

export const ICONS = {
  "data.clear-all-filters": "filter-clear",
  "data.clear-my-view": "sheet-view-exit",
  "data.column-stats": "stats",
  "data.convert-text-to-numbers": "to-number",
  "data.data-validation": "validation",
  "data.filter": "filter",
  "data.group": "group",
  "data.group.collapse-all": "collapse",
  "data.group.expand-all": "expand",
  "data.group.group-columns": "group-cols",
  "data.group.group-rows": "group-rows",
  "data.group.show-level-1": "level-1",
  "data.group.show-level-2": "level-2",
  "data.group.ungroup-columns": "ungroup-cols",
  "data.group.ungroup-rows": "ungroup-rows",
  "data.hide-columns": "hide-col",
  "data.hide-rows": "hide-row",
  "data.pivottable-fields": "pivot-source",
  "data.refresh-all-pivots": "refresh-all",
  "data.refresh-pivot": "refresh",
  "data.remove-duplicates": "duplicate",
  "data.sort-range": "sort",
  "data.sort-range.a-z": "sort-asc",
  "data.sort-range.custom-sort": "sort-custom",
  "data.sort-range.z-a": "sort-desc",
  "data.text-to-columns": "convert",
  "data.unhide-all-rows-and-columns": "expand",
  "data.unhide-rows-columns-in-selection": "expand",
  "edit.clear": "clear",
  "edit.clear.all": "clear-all",
  "edit.clear.contents": "clear-values",
  "edit.clear.formats": "clear-format",
  "edit.copy": "copy",
  "edit.cut": "cut",
  "edit.fill": "fill-down",
  "edit.fill.fill-down": "fill-down",
  "edit.fill.fill-right": "fill-right",
  "edit.fill.fill-series": "growth",
  "edit.find-replace": "find",
  "edit.go-to": "select",
  "edit.paste": { i: "clip", l: "paste" },
  "edit.paste-formats": "paste-formats",
  "edit.paste-formulas": "paste-formulas",
  "edit.paste-special": "paste-special",
  "edit.paste-transpose": "transpose",
  "edit.paste-values": "paste-values",
  "edit.redo": "redo",
  "edit.replace": "replace",
  "edit.select-all": "select-all",
  "edit.select-commented": "select-comments",
  "edit.undo": "undo",
  "file.download": "export",
  "file.export-as-pdf": "pdf",
  "file.new": "file-new",
  "file.open": "folder-open",
  "file.page-break-here": "view-breaks",
  "file.page-setup": "view-page",
  "file.print": "print",
  "file.properties": "properties",
  "file.save": "save",
  "file.share": "share",
  "file.version-history": "history",
  "format.alignment.bottom": "al-bot",
  "format.alignment.center": "al-center",
  "format.alignment.fill-repeat-text": "al-fill",
  "format.alignment.justify-vertical": "al-vjust",
  "format.alignment.left": "al-left",
  "format.alignment.middle": "al-mid",
  "format.alignment.right": "al-right",
  "format.alignment.top": "al-top",
  "format.autofit-column": "autofit-col",
  "format.autofit-row": "autofit-row",
  "format.bold": "bold",
  "format.cell-styles": "style-new",
  "format.column-width": "col-width",
  "format.conditional-formatting": "cf-highlight",
  "format.conditional-formatting-rules": "cf-manage",
  "format.custom-number-format": "numfmt",
  "format.format-cells": "format-cells",
  "format.italic": "italic",
  "format.number": "nf-number",
  "format.protection.hide-formula": "formula-hide",
  "format.protection.locked": "lock",
  "format.protection.protect-this-sheet": "lock",
  "format.row-height": "height",
  "format.strikethrough": "strike",
  "format.subscript": "sub",
  "format.superscript": "super",
  "format.text-overflow.wrap": "wrap",
  "format.trace.trace-dependents": "trace-dep",
  "format.trace.trace-precedents": "trace-prec",
  "format.underline": "underline",
  "formulas.define-name": "name-define",
  "formulas.insert-function": "fx",
  "formulas.name-manager": "name-manager",
  "help.about": "help",
  "help.keyboard-shortcuts": "keyboard",
  "home.cells.format": "format-cells",
  "home.styles.format-as-table": "table",
  "insert.cells": "ins-cells",
  "insert.chart": "chart",
  "insert.chart.area": "chart-area",
  "insert.chart.bar": "chart-bar",
  "insert.chart.column": "chart-column",
  "insert.chart.doughnut": "chart-doughnut",
  "insert.chart.line": "chart-line",
  "insert.chart.pie": "chart-pie",
  "insert.chart.scatter": "chart-scatter",
  "insert.columns-left": "ins-coll",
  "insert.columns-right": "ins-colr",
  "insert.delete-cells": "del-cells",
  "insert.delete-columns": "del-col",
  "insert.delete-rows": "del-row",
  "insert.hyperlink": "link",
  "insert.hyperlink.edit": "link-edit",
  "insert.image": "shapes",
  "insert.note": "note",
  "insert.note.show": "comments-show",
  "insert.pivottable": "pivot",
  "insert.rows-above": "ins-rowa",
  "insert.rows-below": "ins-rowb",
  "insert.sheet": "sheet-view-new",
  "insert.table": "table",
  "table.convert-to-range": "table-to-range",
  "toolbar.bold": "bold",
  "toolbar.border": "borders",
  "toolbar.comma": "comma",
  "toolbar.currency": "nf-accounting",
  "toolbar.dec-dec": "nf-number",
  "toolbar.delete-sheet": "del-row",
  "toolbar.fillcolor": "fill-color",
  "toolbar.filter": "filter",
  "toolbar.font": "font",
  "toolbar.fontcolor": "font-color",
  "toolbar.freeze": "freeze",
  "toolbar.inc-dec": "nf-number",
  "toolbar.indent-less": "indent-less",
  "toolbar.indent-more": "indent-more",
  "toolbar.italic": "italic",
  "toolbar.merge": "merge-center",
  "toolbar.numfmt": "numfmt",
  "toolbar.numfmt-label": "numfmt",
  "toolbar.painter": "painter",
  "toolbar.percent": "percent",
  "toolbar.redo": "redo",
  "toolbar.rotate": "rotate-object",
  "toolbar.size": "font",
  "toolbar.size-down": "font-down",
  "toolbar.size-up": "font-up",
  "toolbar.sort": "sort",
  "toolbar.strike": "strike",
  "toolbar.underline": "underline",
  "toolbar.undo": "undo",
  "toolbar.valign": "al-mid",
  "toolbar.wrap": "wrap",
  "tools.calculation": "calc-options",
  "tools.calculation.automatic": "calc-auto",
  "tools.calculation.calculate-now": "calc-now",
  "tools.calculation.manual": "calc-manual",
  "tools.name-manager": "name-manager",
  "tools.settings": "gear",
  "view.cell-markings": "headings",
  "view.formulas-instead-of-results": "formula-hide",
  "view.freeze.first-column": "freeze-col",
  "view.freeze.top-row": "freeze-row",
  "view.freeze.unfreeze": "unfreeze",
  "view.freeze.up-to-selection": "freeze-sel",
  "view.gridlines": "gridlines",
  "view.settings": "gear",
  "view.theme": "view-normal",
  "view.zero-values": "nf-number",
  "view.zoom": "zoom",
};

/// The `<symbol>` ids to try for a command, best first.
///
/// **A size is a preference, not a guarantee.** Only 39 of these names have a
/// 20px `l-` variant, so asking for one unconditionally produced nine dangling
/// `<use href="#l-…">` — which render as nothing at all, silently, because a
/// broken `use` is not an error. The caller takes the first id the sprite
/// actually defines; a 16px glyph drawn at 20 is still the right picture.
export function iconIds(cmd, large) {
  const e = ICONS[cmd];
  if (!e) return [];
  const i = typeof e === "string" ? e : e.i;
  const l = typeof e === "string" ? e : e.l;
  return large ? [`l-${l}`, `i-${i}`] : [`i-${i}`, `l-${l}`];
}
